### ISSUE TITLE
Integrated server startup exception

### ISSUE THREAD

**Issue by RAnders00** [jakimfett/Minechem#716]
This does not crash (by way of exiting Minecraft). When trying to join/create a singleplayer world, this is put into the log and you are being returned to the title screen.
https://gist.github.com/RAnders00/84260e11a596b1fdf693
Thermal Expansion 4.0.0RC7-164
Thermal Foundation 1.0.0RC7-72
Minechem 5.0.5.394 (got the latest from the jenkins server)
CoFH Core 3.0.0RC7-242
CoFHLib 1.0.0RC7-142

**Comment by way2muchnoise** [comment]
@RAnders00 Does it crash without minechem? Does it crash with only minechem (and it's deps ofc)?

**Comment by RAnders00** [comment]
It is indeed a Minechem-issue. If you look into the log you see:
[19:23:31] [Client thread/WARN] [FML]: ****************************************
[19:23:31] [Client thread/WARN] [FML]: * Duplicate registration attempt for fluid mt (type minechem.fluid.FluidMolecule) has occurred. This is not a problem itself, but subsequent failed FluidStacks might be a result if not handled properly
[19:23:31] [Client thread/WARN] [FML]: *  at net.minecraftforge.fluids.FluidRegistry.registerFluid(FluidRegistry.java:84)
[19:23:31] [Client thread/WARN] [FML]: *  at minechem.fluid.MinechemFluid.<init>(MinechemFluid.java:21)
[19:23:31] [Client thread/WARN] [FML]: *  at minechem.fluid.FluidMolecule.<init>(FluidMolecule.java:17)
[19:23:31] [Client thread/WARN] [FML]: *  at minechem.fluid.FluidHelper.registerMolecule(FluidHelper.java:32)
[19:23:31] [Client thread/WARN] [FML]: *  at minechem.item.molecule.MoleculeEnum.registerMolecule(MoleculeEnum.java:311)
[19:23:31] [Client thread/WARN] [FML]: *  at minechem.item.molecule.MoleculeEnum.addMolecule(MoleculeEnum.java:297)...
[19:23:31] [Client thread/WARN] [FML]: ****************************************

**Comment by way2muchnoise** [comment]
@RAnders00 Well if it crashes with TE doing things with maybe it is TEs fault?

**Comment by RAnders00** [comment]
Then it's probably worth a crosspost on CoFH/Feedback#408

**Comment by KingLemming** [comment]
Forge 1355 and higher have a revamped Fluid system. It's about 99% compatible. Until mods update to the new Forges, I recommend NOT using it.

**Comment by way2muchnoise** [comment]
Well if it is as @KingLemming states then downgrading to the recommended forge version (which is 10.13.2.1291) should fix the issue

**Comment by jakimfett** [comment]
We shouldn't register empty fluidstacks. That's bad, and we should feel bad. Off the top of my head, we should check if a registered fluid has a null stack, and if it does, un-register it.

**Comment by RAnders00** [comment]
I have recently updated my mods and one of them now requires something above forge 1291. If it is possible to just put some null checks in, that would be absolutely lovely.

**Comment by way2muchnoise** [comment]
This should be fixed in #719

**Comment by jakimfett** [comment]
Minechem builds below 395 are built against Forge 10.13.2.1291, because Forge versions later than this implement a bunch of changes to how fluids are handled.

To fix this, either update to Minechem build 395+ (which may be unstable, you have been warned...), or revert back to a supported version of Forge.
