### ISSUE TITLE
Minechem Crashes! PLEASE HELP!!

### ISSUE THREAD

**Issue by VenomRaptor** [jakimfett/Minechem#727]
Hey, every time I try opening minecraft and playing on a world, it crashes and gives a crash report. I have the mods Minechem, CoFHLib, and Buildcraft installed. Is there anything else I need or anything I can do to fix it? I really want to play Minechem. Thanks

**Comment by way2muchnoise** [comment]
@VenomRaptor Can we have the crash report?

**Comment by drago15243** [comment]
same happened to me http://pastebin.com/Ytd5PMf1

**Comment by jakimfett** [comment]
@VenomRaptor could I get you to look over the [Bug Reporting Guidelines](https://github.com/jakimfett/Minechem/wiki/Bug-Reporting) and update your bug report?

@drago15243 please open an individual bug report for your problem. Without a crash report, there's no way to determine if your crash is the same (or even similar) to the one reported by VenomRaptor.

**Comment by Reece-B** [comment]
I got the same thing and minechem and cofh lib were the only mods i had. Here is my crash report:
---- Minecraft Crash Report ----
// I let you down. Sorry :(

Time: 4/25/15 12:16 AM
Description: Updating screen events

java.lang.IllegalStateException: The fluid registry is corrupted
	at net.minecraftforge.fluids.FluidRegistry.getDefaultFluidName(FluidRegistry.java:294)
	at net.minecraftforge.fluids.FluidRegistry.writeDefaultFluidList(FluidRegistry.java:324)
	at net.minecraftforge.common.ForgeModContainer.getDataForWriting(ForgeModContainer.java:314)
	at cpw.mods.fml.common.FMLCommonHandler.handleWorldDataSave(FMLCommonHandler.java:375)
	at net.minecraft.world.storage.SaveHandler.func_75761_a(SaveHandler.java:209)
	at net.minecraft.client.Minecraft.func_71371_a(Minecraft.java:2081)
	at net.minecraft.client.gui.GuiCreateWorld.func_146284_a(GuiCreateWorld.java:230)
	at net.minecraft.client.gui.GuiScreen.func_73864_a(GuiScreen.java:225)
	at net.minecraft.client.gui.GuiCreateWorld.func_73864_a(GuiCreateWorld.java:377)
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:296)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:268)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1640)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.minecraftforge.fluids.FluidRegistry.getDefaultFluidName(FluidRegistry.java:294)
	at net.minecraftforge.fluids.FluidRegistry.writeDefaultFluidList(FluidRegistry.java:324)
	at net.minecraftforge.common.ForgeModContainer.getDataForWriting(ForgeModContainer.java:314)
	at cpw.mods.fml.common.FMLCommonHandler.handleWorldDataSave(FMLCommonHandler.java:375)
	at net.minecraft.world.storage.SaveHandler.func_75761_a(SaveHandler.java:209)
	at net.minecraft.client.Minecraft.func_71371_a(Minecraft.java:2081)
	at net.minecraft.client.gui.GuiCreateWorld.func_146284_a(GuiCreateWorld.java:230)
	at net.minecraft.client.gui.GuiScreen.func_73864_a(GuiScreen.java:225)
	at net.minecraft.client.gui.GuiCreateWorld.func_73864_a(GuiCreateWorld.java:377)
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:296)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:268)

-- Affected screen --
Details:
	Screen name: net.minecraft.client.gui.GuiMainMenu
Stacktrace:
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1640)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 8 (amd64) version 6.2
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 729094344 bytes (695 MB) / 825229312 bytes (787 MB) up to 1908932608 bytes (1820 MB)
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2048m -Xms256m -XX:PermSize=256m
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.127.1393 Minecraft Forge 10.13.3.1393 4 mods loaded, 4 mods active
	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	FML{7.10.127.1393} [Forge Mod Loader] (forge-1.7.10-10.13.3.1393-1710ls.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	Forge{10.13.3.1393} [Minecraft Forge] (forge-1.7.10-10.13.3.1393-1710ls.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	minechem{5.0.5.394} [Minechem] (Minechem-1.7.10-5.0.5.394.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	GL info: ' Vendor: 'Intel' Version: '4.0.0 - Build 10.18.10.3379' Renderer: 'Intel(R) HD Graphics 4000'
	Launched Version: forge-10.13.3.1393
	LWJGL: 2.9.1
	OpenGL: Intel(R) HD Graphics 4000 GL version 4.0.0 - Build 10.18.10.3379, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: []
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: Off (1)

I hope this helps.

**Comment by way2muchnoise** [comment]
@Reece-B When using forge 1355+ use the latest dev build from [Jenkins](http://jenkins.jakimfett.com/job/Minechem%20v5%20for%201.7.10/) or revert to the recommended version of forge

**Comment by jakimfett** [comment]
You're using an unsupported, bleeding edge, development version of Forge.

Please revert to the recommended Forge version (currently 10.13.2.1291), or download a Minechem development build from the Minechem Jenkins server (may contain bugs).

**Comment by Reece-B** [comment]
Thank you so much Jakimfett it worked!
