### ISSUE TITLE
Java 1.8 crash: SoftHashMap uses sun.misc

### ISSUE THREAD

**Issue by truthspirit** [jakimfett/Minechem#739]
The sun.misc package is being removed from java 1.8.

The sun.misc.Hashing algorithms were not performant on multi-core systems so the usage of this was generally deprecated in practice.

I suggest removing these optimizations as they reduce forward-compatibility and are of dubious value on modern hardware.

I know you guys aren't working on Java8 compatibility current, so I will write a pull request for this soon.

```
[19:23:18] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.util.ReportedException: Ticking player
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:181) ~[nc.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659) ~[MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) ~[MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111) ~[bsx.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [?:?]
Caused by: java.lang.NoClassDefFoundError: sun/misc/Hashing
	at minechem.utils.SoftHashMap.<init>(SoftHashMap.java:72) ~[SoftHashMap.class:?]
	at minechem.utils.SoftHashMap.<init>(SoftHashMap.java:115) ~[SoftHashMap.class:?]
	at minechem.radiation.RadiationMoleculeHandler.<init>(RadiationMoleculeHandler.java:47) ~[RadiationMoleculeHandler.class:?]
	at minechem.radiation.RadiationMoleculeHandler.getInstance(RadiationMoleculeHandler.java:36) ~[RadiationMoleculeHandler.class:?]
	at minechem.radiation.RadiationHandler.decayElement(RadiationHandler.java:236) ~[RadiationHandler.class:?]
	at minechem.radiation.RadiationHandler.updateRadiation(RadiationHandler.java:212) ~[RadiationHandler.class:?]
	at minechem.radiation.RadiationHandler.updateRadiationOnItems(RadiationHandler.java:129) ~[RadiationHandler.class:?]
	at minechem.radiation.RadiationHandler.updateRadiationOnItems(RadiationHandler.java:102) ~[RadiationHandler.class:?]
	at minechem.radiation.RadiationHandler.updateContainer(RadiationHandler.java:97) ~[RadiationHandler.class:?]
	at minechem.radiation.RadiationHandler.update(RadiationHandler.java:55) ~[RadiationHandler.class:?]
	at minechem.tick.ScheduledTickHandler.tick(ScheduledTickHandler.java:23) ~[ScheduledTickHandler.class:?]
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_479_ScheduledTickHandler_tick_PlayerTickEvent.invoke(.dynamic) ~[?:?]
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) ~[ASMEventHandler.class:?]
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138) ~[EventBus.class:?]
	at cpw.mods.fml.common.FMLCommonHandler.onPlayerPreTick(FMLCommonHandler.java:345) ~[FMLCommonHandler.class:?]
	at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:220) ~[yz.class:?]
	at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:295) ~[mw.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147347_a(NetHandlerPlayServer.java:303) ~[nh.class:?]
	at net.minecraft.network.play.client.C03PacketPlayer.func_148833_a(SourceFile:137) ~[jd.class:?]
	at net.minecraft.network.play.client.C03PacketPlayer$C04PacketPlayerPosition.func_148833_a(SourceFile:63) ~[je.class:?]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) ~[ej.class:?]
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165) ~[nc.class:?]
	... 5 more
Caused by: java.lang.ClassNotFoundException: sun.misc.Hashing
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[?:1.8.0_60-ea]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_60-ea]
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331) ~[?:1.8.0_60-ea]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_60-ea]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:106) ~[launchwrapper-1.11.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_60-ea]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_60-ea]
	at minechem.utils.SoftHashMap.<init>(SoftHashMap.java:72) ~[SoftHashMap.class:?]
	at minechem.utils.SoftHashMap.<init>(SoftHashMap.java:115) ~[SoftHashMap.class:?]
	at minechem.radiation.RadiationMoleculeHandler.<init>(RadiationMoleculeHandler.java:47) ~[RadiationMoleculeHandler.class:?]
	at minechem.radiation.RadiationMoleculeHandler.getInstance(RadiationMoleculeHandler.java:36) ~[RadiationMoleculeHandler.class:?]
	at minechem.radiation.RadiationHandler.decayElement(RadiationHandler.java:236) ~[RadiationHandler.class:?]
	at minechem.radiation.RadiationHandler.updateRadiation(RadiationHandler.java:212) ~[RadiationHandler.class:?]
	at minechem.radiation.RadiationHandler.updateRadiationOnItems(RadiationHandler.java:129) ~[RadiationHandler.class:?]
	at minechem.radiation.RadiationHandler.updateRadiationOnItems(RadiationHandler.java:102) ~[RadiationHandler.class:?]
	at minechem.radiation.RadiationHandler.updateContainer(RadiationHandler.java:97) ~[RadiationHandler.class:?]
	at minechem.radiation.RadiationHandler.update(RadiationHandler.java:55) ~[RadiationHandler.class:?]
	at minechem.tick.ScheduledTickHandler.tick(ScheduledTickHandler.java:23) ~[ScheduledTickHandler.class:?]
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_479_ScheduledTickHandler_tick_PlayerTickEvent.invoke(.dynamic) ~[?:?]
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) ~[ASMEventHandler.class:?]
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138) ~[EventBus.class:?]
	at cpw.mods.fml.common.FMLCommonHandler.onPlayerPreTick(FMLCommonHandler.java:345) ~[FMLCommonHandler.class:?]
	at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:220) ~[yz.class:?]
	at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:295) ~[mw.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147347_a(NetHandlerPlayServer.java:303) ~[nh.class:?]
	at net.minecraft.network.play.client.C03PacketPlayer.func_148833_a(SourceFile:137) ~[jd.class:?]
	at net.minecraft.network.play.client.C03PacketPlayer$C04PacketPlayerPosition.func_148833_a(SourceFile:63) ~[je.class:?]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) ~[ej.class:?]
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165) ~[nc.class:?]
	... 5 more
```

**Comment by jakimfett** [comment]
Please open a new issue after reading through the [Bug Reporting Guidelines](https://github.com/jakimfett/Minechem/wiki/Bug-Reporting-Guidelines) if you continue to have problems with this.
