### ISSUE TITLE
Fluid Registry Corrupted

### ISSUE THREAD

**Issue by thebrightspark** [jakimfett/Minechem#744]
When I add Minechem to my private modpack, I crash after about 30s with the following error:

[19:09:57] [Server thread/ERROR] [FML/]: The fluid registry is corrupted. A fluid minechem.fluid.FluidElement mt is not properly registered. The mod that registered this is broken
[19:09:57] [Client thread/INFO] [STDOUT/]: [net.minecraft.client.Minecraft:func_71377_b:349]: ---- Minecraft Crash Report ----
// Shall we play a game?

Time: 29/04/15 19:09
Description: Exception in server tick loop

java.lang.IllegalStateException: The fluid registry is corrupted
	at net.minecraftforge.fluids.FluidRegistry.getDefaultFluidName(FluidRegistry.java:294)
	at net.minecraftforge.fluids.FluidRegistry.writeDefaultFluidList(FluidRegistry.java:324)
	at net.minecraftforge.common.ForgeModContainer.getDataForWriting(ForgeModContainer.java:314)
	at cpw.mods.fml.common.FMLCommonHandler.handleWorldDataSave(FMLCommonHandler.java:375)
	at net.minecraft.world.storage.SaveHandler.func_75755_a(SaveHandler.java:169)
	at net.minecraft.world.chunk.storage.AnvilSaveHandler.func_75755_a(AnvilSaveHandler.java:41)
	at net.minecraft.world.WorldServer.func_73042_a(WorldServer.java:837)
	at net.minecraft.world.WorldServer.func_73044_a(WorldServer.java:802)
	at net.minecraft.server.MinecraftServer.func_71267_a(MinecraftServer.java:318)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:569)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

That's all I feel may be necessary to include in this report, but if any other information is required, please shout.

**Comment by jakimfett** [comment]
You're using an unsupported, bleeding edge, development version of Forge.

Please revert to the recommended Forge version (currently 10.13.2.1291), or download a Minechem development build from the Minechem Jenkins server (may contain bugs).

**Comment by thebrightspark** [comment]
Ah I see, that makes a lot of sense. Thanks :)

**Comment by walkerjonny** [comment]
Well, many major mods are switching now to Forge Build 1355+ because of the new Fluid system.
Buildcraft, Railcraft, Mekanism, TE, GregTech 5.08.xx,...
Some of them also require Forge Builds around 1390.
So it would make sense to release a new Minechem version.
