### ISSUE TITLE
Radioactive elements that end up in a normal chest causing a crash 

### ISSUE THREAD

**Issue by yarma92** [jakimfett/Minechem#747]
Radioactive elements or compounds that end up in a normal chest causing a crash when opening the inventory they are in. When break the chest and picking up the offending chemical the player repeatedly crashes on loading into the world.

Crash logs below.
Chest crash log:
[code]
---- Minecraft Crash Report ----
// Ouch. That hurt :(

Time: 03/05/15 19:42
Description: Ticking player

java.lang.NoClassDefFoundError: sun/misc/Hashing
    at minechem.utils.SoftHashMap.<init>(SoftHashMap.java:72)
    at minechem.utils.SoftHashMap.<init>(SoftHashMap.java:115)
    at minechem.radiation.RadiationMoleculeHandler.<init>(RadiationMoleculeHandler.java:47)
    at minechem.radiation.RadiationMoleculeHandler.getInstance(RadiationMoleculeHandler.java:36)
    at minechem.radiation.RadiationHandler.decayElement(RadiationHandler.java:236)
    at minechem.radiation.RadiationHandler.updateRadiation(RadiationHandler.java:212)
    at minechem.radiation.RadiationHandler.updateRadiationOnItems(RadiationHandler.java:129)
    at minechem.radiation.RadiationHandler.updateRadiationOnItems(RadiationHandler.java:102)
    at minechem.radiation.RadiationHandler.updateContainer(RadiationHandler.java:97)
    at minechem.radiation.RadiationHandler.update(RadiationHandler.java:55)
    at minechem.tick.ScheduledTickHandler.tick(ScheduledTickHandler.java:23)
    at cpw.mods.fml.common.eventhandler.ASMEventHandler_473_ScheduledTickHandler_tick_PlayerTickEvent.invoke(.dynamic)
    at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
    at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
    at cpw.mods.fml.common.FMLCommonHandler.onPlayerPreTick(FMLCommonHandler.java:345)
    at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:220)
    at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:295)
    at net.minecraft.network.NetHandlerPlayServer.func_147347_a(NetHandlerPlayServer.java:303)
    at net.minecraft.network.play.client.C03PacketPlayer.func_148833_a(SourceFile:137)
    at net.minecraft.network.play.client.C03PacketPlayer$C05PacketPlayerLook.func_148833_a(SourceFile:98)
    at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
    at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
    at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
    at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
Caused by: java.lang.ClassNotFoundException: sun.misc.Hashing
    at java.net.URLClassLoader$1.run(URLClassLoader.java:372)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:360)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:106)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    ... 27 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
    at minechem.utils.SoftHashMap.<init>(SoftHashMap.java:72)
    at minechem.utils.SoftHashMap.<init>(SoftHashMap.java:115)
    at minechem.radiation.RadiationMoleculeHandler.<init>(RadiationMoleculeHandler.java:47)
    at minechem.radiation.RadiationMoleculeHandler.getInstance(RadiationMoleculeHandler.java:36)
    at minechem.radiation.RadiationHandler.decayElement(RadiationHandler.java:236)
    at minechem.radiation.RadiationHandler.updateRadiation(RadiationHandler.java:212)
    at minechem.radiation.RadiationHandler.updateRadiationOnItems(RadiationHandler.java:129)
    at minechem.radiation.RadiationHandler.updateRadiationOnItems(RadiationHandler.java:102)
    at minechem.radiation.RadiationHandler.updateContainer(RadiationHandler.java:97)
    at minechem.radiation.RadiationHandler.update(RadiationHandler.java:55)
    at minechem.tick.ScheduledTickHandler.tick(ScheduledTickHandler.java:23)
    at cpw.mods.fml.common.eventhandler.ASMEventHandler_473_ScheduledTickHandler_tick_PlayerTickEvent.invoke(.dynamic)
    at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
    at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
    at cpw.mods.fml.common.FMLCommonHandler.onPlayerPreTick(FMLCommonHandler.java:345)
    at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:220)

-- Player being ticked --
Details:
    Entity Type: null (net.minecraft.entity.player.EntityPlayerMP)
    Entity ID: 18
    Entity Name: deathxp100
    Entity's Exact location: 0.26, 109.00, -7.14
    Entity's Block location: World: (0,109,-8), Chunk: (at 0,6,8 in 0,-1; contains blocks 0,0,-16 to 15,255,-1), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
    Entity's Momentum: 0.00, -0.08, 0.00
Stacktrace:
    at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:295)
    at net.minecraft.network.NetHandlerPlayServer.func_147347_a(NetHandlerPlayServer.java:303)
    at net.minecraft.network.play.client.C03PacketPlayer.func_148833_a(SourceFile:137)
    at net.minecraft.network.play.client.C03PacketPlayer$C05PacketPlayerLook.func_148833_a(SourceFile:98)
    at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)

-- Ticking connection --
Details:
    Connection: net.minecraft.network.NetworkManager@5dd611f1
Stacktrace:
    at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
    at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
    at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

-- System Details --
Details:
    Minecraft Version: 1.7.10
    Operating System: Windows 8.1 (amd64) version 6.3
    Java Version: 1.8.0_25, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 1450619984 bytes (1383 MB) / 1930952704 bytes (1841 MB) up to 3817865216 bytes (3641 MB)
    JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4096m -Xms256m -XX:PermSize=256m
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    FML: MCP v9.05 FML v7.10.103.1352 Minecraft Forge 10.13.2.1352 68 mods loaded, 68 mods active
    mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    FML{7.10.103.1352} [Forge Mod Loader] (forge-1.7.10-10.13.2.1352-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Forge{10.13.2.1352} [Minecraft Forge] (forge-1.7.10-10.13.2.1352-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    appliedenergistics2-core{rv2-beta-2} [AppliedEnergistics2 Core] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    CodeChickenCore{1.0.4.35} [CodeChicken Core] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    <CoFH ASM>{000} [CoFH ASM Data Initialization] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    MobiusCore{1.2.5} [MobiusCore] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    NotEnoughItems{1.0.4.95} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.4.95-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    OpenModsCore{0.7.1} [OpenModsCore] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    bspkrsCore{6.15} [bspkrsCore] ([1.7.10]bspkrsCore-universal-6.15.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    appliedenergistics2{rv2-beta-2} [Applied Energistics 2] (appliedenergistics2-rv2-beta-2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Baubles{1.0.1.10} [Baubles] (Baubles-1.7.10-1.0.1.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    aura{0.1r0} [Aura Cascade] (AuraCascade-357.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    bettersugarcane{2.0a} [Better Sugar Cane] (bettersugarcane--1.7.10-2.0a.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    CoFHCore{1.7.10R3.0.0B9} [CoFH Core] (CoFHCore-[1.7.10]3.0.0B9-40.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Waila{1.5.10} [Waila] (Waila-1.5.10_1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Calculator{Universal} [Calculator] (Calculator-1.7.10-1.6.7.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    CarpentersBlocks{3.3.6} [Carpenter's Blocks] (Carpenter's Blocks v3.3.6 - MC 1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ChickenChunks{1.3.4.16} [ChickenChunks] (ChickenChunks-1.7.10-1.3.4.16-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    chisel{2.3.10.37} [Chisel 2] (Chisel2-2.3.10.37.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    CompactMachines{1.7.10-1.18} [Compact Machines] (compactmachines-1.7.10-1.18.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    customitems{1.0.9b} [Meta Mod: Custom Items] (customitems-1.0.9_beta_1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    CustomMainMenu{1.4} [Custom Main Menu] (CustomMainMenu-MC1.7.10-1.4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    defaultworldgenerator{0.1-b13} [Default World Generator] (DefaultWorldGenerator-1.7.10-0.1-b13-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    EnderIO{1.7.10-2.2.8.367} [Ender IO] (EnderIO-1.7.10-2.2.8.367.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ThermalFoundation{1.7.10R1.0.0RC1} [Thermal Foundation] (ThermalFoundation-[1.7.10]1.0.0RC1-13.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ThermalExpansion{1.7.10R4.0.0B8} [Thermal Expansion] (ThermalExpansion-[1.7.10]4.0.0B8-23.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    EnderTech{1.7.10-0.3.2.382} [EnderTech] (EnderTech-1.7.10-0.3.2.382.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    EE3{0.2.461} [Equivalent Exchange 3] (EquivalentExchange3-1.7.10-0.2.461.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    extracells{2.2.64} [ExtraCells] (ExtraCells-1.7.10-2.2.64b96.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ExtraUtilities{1.2.1} [Extra Utilities] (extrautilities-1.2.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    MineTweaker3{3.0.9B} [MineTweaker 3] (MineTweaker3-1.7.10-3.0.9C.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ttCore{MC1.7.10-0.1.1-76} [ttCore] (ttCore-MC1.7.10-0.1.1-76.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    fluxedcrystals{0.0.5j} [Fluxed-Crystals] (fluxedCrystals-0.0.5j.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    FruitCharcoal{1.7.10-1.1} [Fruit Charcoal] (fruitcharcoal-1.7.10-1.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    futuristic decor{1.1} [Futuristic Decor] (futuristicdecor-1.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    headcrumbs{1.3.1} [Headcrumbs] (Headcrumbs-1.3.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    HoloInventory{1.9.0.106} [HoloInventory] (HoloInventory-1.7.10-1.9.0.106.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    HardcoreQuesting{The Journey (4.2.3)} [Hardcore Questing Mode] (HQM-The Journey (4.2.3).jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    iChunUtil{4.2.2} [iChunUtil] (iChunUtil-4.2.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    InventoryPets{1.1.0} [Inventory Pets] (inventorypets-1.7.10-1.1.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    inventorytweaks{1.59-dev-152-cf6e263} [Inventory Tweaks] (InventoryTweaks-1.59-dev-152.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    journeymap{5.0.1} [JourneyMap] (JourneyMap5.0.1_Unlimited_MC1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Mantle{1.7.10-0.3.2.jenkins184} [Mantle] (Mantle-1.7.10-0.3.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    TConstruct{1.7.10-1.8.2.build857} [Tinkers' Construct] (TConstruct-1.7.10-1.8.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    jsonables{1.0.3} [JSONAbles] (JSONAbles-1.0.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Lockdown{2.0.0} [Lockdown] (Lockdown-universal-1.7.2-2.0.0.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    LoreExp{1.0.5} [Lore Expansion] (LoreExpansion-1.7.10-1.0.5.B29a.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    minechem{5.0.5.394} [Minechem] (Minechem-1.7.10-5.0.5.394.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    modtweaker2{0.7} [Mod Tweaker 2] (ModTweaker 2-0.7.5.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    OpenMods{0.7.1} [OpenMods] (OpenModsLib-1.7.10-0.7.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    OpenBlocks{1.4.1} [OpenBlocks] (OpenBlocks-1.7.10-1.4.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    pearcelmod{1.7.10-1.7} [Pearcel Mod] (pearcelmod-1.7.10-1.7-pre.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    PerfectSpawn{1.1} [Perfect Spawn] (PerfectSpawn-1.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    quickhotbar{1.04} [Quick Hotbar] (quickhotbar_1710_1.04.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    randomite{2.0} [Randomite] (randomite-2.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    RandomThings{2.2.4} [Random Things] (RandomThings-2.2.4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ResourceLoader{1.1} [Resource Loader] (ResourceLoader-1.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    sprinkles_for_vanilla{1.2.0beta} [sprinkles_for_vanilla] (sprinklesforvanilla-1.7.10-1.2.0beta.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    StevesFactoryManager{A93} [Steve's Factory Manager] (StevesFactoryManagerA93.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    superMassiveTech{0.2.0-alpha} [Super Massive Tech] (SuperMassiveTech-MC1.7.10-0.2.0-alpha-86.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Sync{4.0.0} [Sync] (Sync-4.0.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    TiCTooltips{1.2.4} [TiC Tooltips] (TiCTooltips-mc1.7.10-1.2.4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    TMechworks{0.2.14.100} [Tinkers' Mechworks] (TMechworks-1.7.10-0.2.14.100.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Torcherino{1.9s} [Torcherino] (Torcherino-1.7.10-1.91s.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    wailafeatures{0.0.1} [WAILA Features] (WAILA-features-1.7.10-0.0.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Ztones{1.7.10} [Ztones] (Ztones-1.7.10-2.2.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    IguanaTweaksTConstruct{1.7.10-2.1.2.101} [Iguana Tinker Tweaks] (IguanaTinkerTweaks-1.7.10-2.1.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    OpenModsLib class transformers: [stencil_patches:FINISHED],[movement_callback:FINISHED],[map_gen_fix:FINISHED],[gl_capabilities_hook:FINISHED],[player_render_hook:FINISHED]
    AE2 Version: beta rv2-beta-2 for Forge 10.13.2.1230
    Mantle Environment: Environment healthy.
    TConstruct Environment: Environment healthy.
    Stencil buffer state: Function set: GL30, pool: internal, bits: 8
    AE2 Integration: IC2:OFF, RotaryCraft:OFF, RC:OFF, BC:OFF, MJ6:OFF, MJ5:OFF, RF:ON, RFItem:ON, MFR:OFF, DSU:ON, FZ:OFF, FMP:OFF, RB:OFF, CLApi:OFF, Waila:ON, InvTweaks:ON, NEI:ON, CraftGuide:OFF, Mekanism:OFF, ImmibisMicroblocks:OFF, BetterStorage:OFF
    Profiler Position: N/A (disabled)
    Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    Player Count: 1 / 8; [EntityPlayerMP['deathxp100'/18, l='ME-^1', x=0.26, y=109.00, z=-7.14]]
    Type: Integrated Server (map_client.txt)
    Is Modded: Definitely; Client brand changed to 'fml,forge'
[/code]

**Comment by way2muchnoise** [comment]
@yarma92 Please use pastebin or a like when posting logs

**Comment by yarma92** [comment]
Sorry I will update it to a pastepin log now

**Comment by jakimfett** [comment]
Could you please read through the [Bug Reporting Guidelines](https://github.com/jakimfett/Minechem/wiki/Bug-Reporting-Guidelines) and update your issue description? Specifically looking for version numbers and whether you can reproduce it with JUST Minechem.
