### ISSUE TITLE
An issue with RotaryCraft

### ISSUE THREAD

**Issue by walkerjonny** [jakimfett/Minechem#750]
I'm playing with the latest Minechem (Jenkins) and the latest DragonAPI / RotaryCraft.

I'm getting frequently but not always this crash at startup.
Unfortunately there is no other crash log, just the following:

[12:49:29] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: java.lang.ClassNotFoundException: Reika.RotaryCraft.Auxiliary.WorktableRecipes
[12:49:29] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
[12:49:29] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.lang.ClassLoader.loadClass(Unknown Source)
[12:49:29] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.lang.ClassLoader.loadClass(Unknown Source)
[12:49:29] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.lang.Class.forName0(Native Method)
[12:49:29] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.lang.Class.forName(Unknown Source)
[12:49:29] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at minechem.utils.Recipe.getRotaryRecipes(Recipe.java:41)
[12:49:29] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at minechem.utils.Recipe.init(Recipe.java:90)
[12:49:29] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at minechem.Minechem.onLoadComplete(Minechem.java:211)
[12:49:29] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[12:49:29] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[12:49:29] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[12:49:29] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[12:49:29] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532)
[12:49:29] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
[12:49:29] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[12:49:29] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[12:49:29] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
[12:49:29] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
[12:49:29] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
[12:49:29] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
[12:49:29] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
[12:49:29] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
[12:49:29] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
[12:49:29] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[12:49:29] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[12:49:29] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[12:49:29] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[12:49:29] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
[12:49:29] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
[12:49:29] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
[12:49:29] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
[12:49:29] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
[12:49:29] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
[12:49:29] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at cpw.mods.fml.common.Loader.initializeMods(Loader.java:720)
[12:49:29] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at cpw.mods.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:309)
[12:49:29] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.client.Minecraft.func_71384_a(Unknown Source)
[12:49:29] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.client.Minecraft.func_99999_d(Unknown Source)
[12:49:29] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.client.main.Main.main(SourceFile:148)
[12:49:29] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[12:49:29] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[12:49:29] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[12:49:29] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[12:49:29] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
[12:49:29] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[12:49:29] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: Caused by: java.lang.NullPointerException

**Comment by way2muchnoise** [comment]
@walkerjonny Plase use pastebin or alike to post logs. Also 
```java.lang.ClassNotFoundException: Reika.RotaryCraft.Auxiliary.WorktableRecipes```
seems like it is a issue for reika

**Comment by way2muchnoise** [comment]
@hilburn This might be one for you. Cause I have no clue how something that loads on world load can't access a class. Except if Reika changed something?

**Comment by walkerjonny** [comment]
That happens not at world loading. It happens at game startup.
But you might be right about that it could be Minechem loading before RotaryCraft.
I renamed the minechem jar with a prefix (zy_minechem jar) and it seems to affect the load order somehow.  
Is there any way to manually and exactly define the load order of mods, for example using a config file?

**Comment by hilburn** [comment]
Reika seems to have refactored - we need to check `Reika.RotaryCraft.Auxiliary.RecipeManagers.WorktableRecipes`

**Comment by walkerjonny** [comment]
Reika's hint about a damaged download was correct. Also sometimes you just need to wait a bit longer and then it continues.
