### ISSUE TITLE
Fluid Registry is Corrupted

### ISSUE THREAD

**Issue by wilfurdmcwargnash** [jakimfett/Minechem#757]
how to reproduce
go into a superflat creative world with the seed 7996320322876153946 (for me at least)

List of Mods
MineChem
Equivalent Exchange 3

what version?
5.0.5.394

Vanilla Cash Report
---- Minecraft Crash Report ----
// Why is it breaking :(

Time: 5/27/15 5:13 PM
Description: Updating screen events

java.lang.IllegalStateException: The fluid registry is corrupted
	at net.minecraftforge.fluids.FluidRegistry.getDefaultFluidName(FluidRegistry.java:294)
	at net.minecraftforge.fluids.FluidRegistry.writeDefaultFluidList(FluidRegistry.java:324)
	at net.minecraftforge.common.ForgeModContainer.getDataForWriting(ForgeModContainer.java:314)
	at cpw.mods.fml.common.FMLCommonHandler.handleWorldDataSave(FMLCommonHandler.java:375)
	at net.minecraft.world.storage.SaveHandler.func_75761_a(SaveHandler.java:209)
	at net.minecraft.client.Minecraft.func_71371_a(Minecraft.java:2081)
	at net.minecraft.client.gui.GuiCreateWorld.func_146284_a(GuiCreateWorld.java:230)
	at net.minecraft.client.gui.GuiScreen.func_73864_a(GuiScreen.java:225)
	at net.minecraft.client.gui.GuiCreateWorld.func_73864_a(GuiCreateWorld.java:377)
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:296)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:268)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1640)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.minecraftforge.fluids.FluidRegistry.getDefaultFluidName(FluidRegistry.java:294)
	at net.minecraftforge.fluids.FluidRegistry.writeDefaultFluidList(FluidRegistry.java:324)
	at net.minecraftforge.common.ForgeModContainer.getDataForWriting(ForgeModContainer.java:314)
	at cpw.mods.fml.common.FMLCommonHandler.handleWorldDataSave(FMLCommonHandler.java:375)
	at net.minecraft.world.storage.SaveHandler.func_75761_a(SaveHandler.java:209)
	at net.minecraft.client.Minecraft.func_71371_a(Minecraft.java:2081)
	at net.minecraft.client.gui.GuiCreateWorld.func_146284_a(GuiCreateWorld.java:230)
	at net.minecraft.client.gui.GuiScreen.func_73864_a(GuiScreen.java:225)
	at net.minecraft.client.gui.GuiCreateWorld.func_73864_a(GuiCreateWorld.java:377)
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:296)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:268)

-- Affected screen --
Details:
	Screen name: net.minecraft.client.gui.GuiMainMenu
Stacktrace:
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1640)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 8.1 (amd64) version 6.3
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 173724464 bytes (165 MB) / 268328960 bytes (255 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.3.1408 7 mods loaded, 7 mods active
	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.3.1408-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	Forge{10.13.3.1408} [Minecraft Forge] (forge-1.7.10-10.13.3.1408-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	<CoFH ASM>{000} [CoFH ASM] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	CoFHCore{1.7.10R3.0.2} [CoFH Core] (CoFHCore-[1.7.10]3.0.2-262.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	EE3{0.3.507} [Equivalent Exchange 3] (EquivalentExchange3-1.7.10-0.3.507.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	minechem{5.0.5.394} [Minechem] (Minechem-1.7.10-5.0.5.394.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	GL info: ' Vendor: 'Intel' Version: '4.0.0 - Build 10.18.10.3304' Renderer: 'Intel(R) HD Graphics'
	CoFHCore: -[1.7.10]3.0.2-262
	Launched Version: 1.7.10-Forge10.13.3.1408-1.7.10
	LWJGL: 2.9.1
	OpenGL: Intel(R) HD Graphics GL version 4.0.0 - Build 10.18.10.3304, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: []
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: Off (1)

Forge Crash Report
Unavailable (It did not create one)

**Comment by way2muchnoise** [comment]
@wilfurdmcwargnash Download a dev build from the [Jenkins](http://jenkins.jakimfett.com/job/Minechem%20v5%20for%201.7.10/) 395 and higher are suitable for forge 1355+

**Comment by jakimfett** [comment]
Before creating issues, please read the [Bug Reporting Guidelines](https://github.com/jakimfett/Minechem/wiki/Bug-Reporting-Guidelines).

Specifically the bits about not pasting logs into the the issue description area...use pastebin or similar.
