### ISSUE TITLE
Can't Play Minechem

### ISSUE THREAD

**Issue by MineMaster284** [jakimfett/Minechem#775]
I can't play Minechem. Can you please help me?
-------------------------------------------------------------------------------------------------------------------------------
---- Minecraft Crash Report ----
// I'm sorry, Dave.

Time: 7/20/15 7:33 AM
Description: Updating screen events

java.lang.IllegalStateException: The fluid registry is corrupted
	at net.minecraftforge.fluids.FluidRegistry.getDefaultFluidName(FluidRegistry.java:297)
	at net.minecraftforge.fluids.FluidRegistry.writeDefaultFluidList(FluidRegistry.java:327)
	at net.minecraftforge.common.ForgeModContainer.getDataForWriting(ForgeModContainer.java:315)
	at cpw.mods.fml.common.FMLCommonHandler.handleWorldDataSave(FMLCommonHandler.java:375)
	at net.minecraft.world.storage.SaveHandler.func_75761_a(SaveHandler.java:209)
	at net.minecraft.client.Minecraft.func_71371_a(Minecraft.java:2081)
	at net.minecraft.client.gui.GuiCreateWorld.func_146284_a(GuiCreateWorld.java:230)
	at net.minecraft.client.gui.GuiScreen.func_73864_a(GuiScreen.java:225)
	at net.minecraft.client.gui.GuiCreateWorld.func_73864_a(GuiCreateWorld.java:377)
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:296)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:268)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1640)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.minecraftforge.fluids.FluidRegistry.getDefaultFluidName(FluidRegistry.java:297)
	at net.minecraftforge.fluids.FluidRegistry.writeDefaultFluidList(FluidRegistry.java:327)
	at net.minecraftforge.common.ForgeModContainer.getDataForWriting(ForgeModContainer.java:315)
	at cpw.mods.fml.common.FMLCommonHandler.handleWorldDataSave(FMLCommonHandler.java:375)
	at net.minecraft.world.storage.SaveHandler.func_75761_a(SaveHandler.java:209)
	at net.minecraft.client.Minecraft.func_71371_a(Minecraft.java:2081)
	at net.minecraft.client.gui.GuiCreateWorld.func_146284_a(GuiCreateWorld.java:230)
	at net.minecraft.client.gui.GuiScreen.func_73864_a(GuiScreen.java:225)
	at net.minecraft.client.gui.GuiCreateWorld.func_73864_a(GuiCreateWorld.java:377)
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:296)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:268)

-- Affected screen --
Details:
	Screen name: net.minecraft.client.gui.GuiMainMenu
Stacktrace:
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1640)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 8.1 (amd64) version 6.3
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 977604176 bytes (932 MB) / 1080557568 bytes (1030 MB) up to 3817865216 bytes (3641 MB)
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4096m -Xms256m -XX:PermSize=256m
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1492 7 mods loaded, 7 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJA	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1492-1.7.10.jar) 
	UCHIJA	Forge{10.13.4.1492} [Minecraft Forge] (forge-1.7.10-10.13.4.1492-1.7.10.jar) 
	UCHIJA	<CoFH ASM>{000} [CoFH ASM] (minecraft.jar) 
	UCHIJA	CoFHCore{1.7.10R3.0.3} [CoFH Core] (CoFHCore-[1.7.10]3.0.3-303.jar) 
	UCHIJA	minechem{5.0.5.394} [Minechem] (Minechem-1.7.10-5.0.5.394.jar) 
	UCHIJA	ThermalFoundation{1.7.10R1.2.0} [Thermal Foundation] (ThermalFoundation-[1.7.10]1.2.0-102.jar) 
	GL info: ' Vendor: 'Intel' Version: '4.3.0 - Build 10.18.14.4029' Renderer: 'Intel(R) HD Graphics 4600'
	CoFHCore: -[1.7.10]3.0.3-303
	ThermalFoundation: -[1.7.10]1.2.0-102
	Launched Version: forge-10.13.4.1492
	LWJGL: 2.9.1
	OpenGL: Intel(R) HD Graphics 4600 GL version 4.3.0 - Build 10.18.14.4029, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: []
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: Off (1)

**Comment by MineMaster284** [comment]
I am playing using the Curse Client(shouldn't make a difference), Windows 8, using only CoFHLib, CoFH Core, and Minechem.

**Comment by way2muchnoise** [comment]
http://minecraft.curseforge.com/mc-mods/73373-minechem/files/2240918
Use this version of minechem when using forge 1355+
This is because of a fluid update on Forges side
